WinWait("Open","",500)
ControlFocus("Open","","Edit1")
Sleep(500)
ControlSetText("Open","","Edit1","F:\Mars\MarsCompetition\MarsCompetition\MarsCompetition\Upload\Dog.png")
ControlClick("Open","","Button1")
Sleep(500)